name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.3
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.2+1
  http: ^0.12.0+2
  equatable: ^1.2.0
  http_parser: ^3.1.4
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^7.0.6
  mockito: ^4.1.2

# The following section is specific to Flutter.
flutter:
